proj_name: mld.run1
analysis_type: -treatment
stat_type: qiime2-default
contact:
  email: nasiegel@ucdavis.edu
  person: Noah Siegel
raw-data: /mnt/c/Users/noahs/projects/tagseq-qiime2-snakemake-1/raw_dir
scratch:  /mnt/c/Users/noahs/projects/tagseq-qiime2-snakemake-1/scratch
outputDIR: /mnt/c/Users/noahs/projects/tagseq-qiime2-snakemake-1/output
home: /mnt/c/Users/noahs/projects/tagseq-qiime2-snakemake-1
metadata: /mnt/c/Users/noahs/projects/tagseq-qiime2-snakemake-1/metadata.tsv
manifest: /mnt/c/Users/noahs/projects/tagseq-qiime2-snakemake-1/raw_dir/manifest-orig.txt
manifest-trimmed: manifest-trimmed.txt

# Fastq file suffix, following the read pair designation
suffix: .fastq.gz
# suffix: _001.fastq.gz

# Read pair designations
#r1_suf: 1
#r2_suf: 2
r1_suf: R1
r2_suf: R2

# QIIME2-specific flags
# Defaults for amplicon tag-sequencing - uncomment only parameters you need.

### Illumina 16S V3-V4 primeres
primerF: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
primerR: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
primer_err: 0.1
primer_overlap: 3 
# Merging reads for 16S
minoverlap: 20
maxdiff: 4
minlength: 200

## Database
database_classified: /mnt/c/Users/noahs/projects/tagseq-qiime2-snakemake-1/database/silva-138-99-nb-classifier_2020.8.qza

## DADA2 - ASV flags
truncation_err: 2
truncation_len-f: 0
truncation_len-r: 0
quality_err: 2
training: 1000 #should be set higher for a non-test dataset
chimera: pooled

## Filter blanks
remove_blanks: 'no' # yes or no
table_blanks: "SampleID IN (
  'BLANK.47453', 'BLANK.47455', 'BLANK.47457', 'BLANK.47467',
''BLANK.47470', 'BLANK.47487', 'BLANK.47505', 'BLANK.47510',
''BLANK.47538', 'BLANK.47548', 'BLANK.47549', 'BLANK.47551',
''BLANK.47552', 'BLANK.47554', 'BLANK.47557', 'BLANK.48381',
''BLANK.48408', 'BLANK.48429'
)" # for preliminary data
metadata_blanks: 'NS.Blank5' # for preliminary data

### phylogeny
metadata_category: "treatment" # , "sex"
alpha-div-p-method: 'spearman' # , "pearson"
beta-div-p-method: 'anosim' # , "permanova", "permdisp"
permutations: 999
# The number of permutations to be run when computing p-values
# For beta indices
sampling-depth: 1000 #should be set higher for a non-test dataset

### picrust2 flags
### To do
#### add ```--p-no-pairwise``` and ```--p-pairwise``` to configuration file
##### date 10/14/20

# longitudinal analysis
perform_longitudinal: 'no' # yes for longitudinal analysis 
state: 'age_months'
studyid: 'animal_number'
replicate: 'random'
test_metadata: 'weight'
group_metadata_category: 'sex, treatment'
control: 'control'
missing_samples: 'ignore'