proj_name: prelim-mld-fecal
raw_data: /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/raw_dir
scratch:  /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/scratch
outputDIR: /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/output
metadata: /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/sample-metadata.tsv
manifest: /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/raw_dir/manifest-orig.txt
manifest-trimmed: manifest-trimmed.txt

# Fastq file suffix, following the read pair designation
suffix: .fastq.gz
# suffix: _001.fastq.gz

# Read pair designations
#r1_suf: 1
#r2_suf: 2
r1_suf: R1
r2_suf: R2

# QIIME2-specific flags
# Defaults for amplicon tag-sequencing - uncomment only parameters you need.

### 18S default (Stoeck et al. 2010 V4 primers)
#primerF: CCAGCASCYGCGGTAATTCC
#primerR: ACTTTCGTTCTTGATYRA
#primer_err: 0.4
#primer_overlap: 3
## Merging reads for 18S:
#minoverlap: 10
#maxdiff: 4
#minlength: 270

## 16S default (Parada et al. modified EMP primers)
primerF: GTGYCAGCMGCCGCGGTAA
primerR: GGACTACNVGGGTWTCTAAT
# Parada et al. 2016 MEP primers for 16S
primer_err: 0.1
primer_overlap: 3 
# Merging reads for 16S
minoverlap: 20
maxdiff: 4
minlength: 200

## Database
database: /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/database/silva-138-99-seqs.qza
database_classified: /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/database/V3-V4-pr2_4.12.0-classifier.qza
database_tax: /home/nasiegel/MLD/tagseq-qiime2-snakemake-1/database/silva-138-99-tax.qza

## DADA2 - ASV flags
truncation_err: 2
truncation_len-f: 0
truncation_len-r: 0
quality_err: 2
training: 1000 #should be set higher for a non-test dataset
chimera: pooled

## OTU clustering

# Quality filtering of merged reads
minphred: 4
qualwindow: 3 

# De novo OTU clustering
denovo_perc_id: 0.97
denovo_otu-thread: 1

# Chimera checking
chimera-thread: 1
