proj_name: prelim-mld-fecal

contact:
  email: nasiegel@ucdavis.edu
  person: Noah Siegel

raw_data: /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/raw_dir
scratch:  /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/scratch
outputDIR: /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/output
metadata: /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/sample-metadata.txt
manifest: /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/raw_dir/manifest-orig.txt
manifest-trimmed: manifest-trimmed.txt

# Fastq file suffix, following the read pair designation
suffix: .fastq.gz
# suffix: _001.fastq.gz

# Read pair designations
#r1_suf: 1
#r2_suf: 2
r1_suf: R1
r2_suf: R2

# QIIME2-specific flags
# Defaults for amplicon tag-sequencing - uncomment only parameters you need.

### Illumina 16S V3-V4 primeres
primerF: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
primerR: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
primer_err: 0.1
primer_overlap: 3 
# Merging reads for 16S
minoverlap: 20
maxdiff: 4
minlength: 200

## Database
database: /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/database/silva-138-99-seqs.qza
database_classified: /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/database/silva-132-99-nb-classifier.qza
database_tax: /mnt/c/Users/noahs/PycharmProjects/tagseq-qiime2-snakemake-1/database/silva-138-99-tax.qza

## DADA2 - ASV flags
truncation_err: 2
truncation_len-f: 0
truncation_len-r: 0
quality_err: 2
training: 1000 #should be set higher for a non-test dataset
chimera: pooled

### phylogeny and analysis flags
metadata-category: sex
# There is only one factor to compare the the moment
alpha-div-p-method: 'spearman'
# Also can be 'pearson'
beta-div-p-method: 'anosim'
# Also can be 'permanova' or 'permdisp'
permutations: 999
# The number of permutations to be run when computing p-values
# For beta indices
sampling-depth: 100 #should be set higher for a non-test dataset
